### ISSUE TITLE
Falta pH

### ISSUE THREAD

**Issue by salicio** [lamberete/lemarioExtactor#1]
He comparado mi listado con tu lemario y parece que se ha escapado un lema:

```
"pH", "SrEA7mp"
```

No he encontrado ningún extraviado más.

**Comment by lamberete** [comment]
Me has pillado!
Asumí que en la RAE las palabras con mayúsculas o bien empezaban por mayúscula o bien eran enteras en mayúsculas. He aquí un contraejemplo 🙈.
Por otro lado también me faltan 2 que contienen î, además de las 2500 (o así) nuevas entradas que han añadido hoy 😅 (que yo sepa)

**Comment by salicio** [comment]
Justo hoy? vaya casualidad pues habrá que volver a procesarlo...

**Comment by lamberete** [comment]
Lo han hecho por fastidiar, seguro 👅

**Comment by lamberete** [comment]
Solucionado con el commit de hoy.
